### PR TITLE
Valencian Language and Spanish Corrections

### PR DESCRIPTION
**Pull request by sontopo**
Added new language, Valencian (as we talked through mails) and some corrections + new strings for spanish.

### CODE REVIEW

**Comment by myConsciousness** [comment]
`aboutHeader3` has already been removed from the template `strings_en.arb`, you can just remove it from `strings_cat.arb` :)

**Comment by myConsciousness** [comment]
@sontopo There seems to be quite a bit of difference from the template. It requires the Dart SDK, but you can remove all unnecessary lines based on the template with the following command and script.

`dart run bin/clean_arb_file.dart`

**Comment by myConsciousness** [comment]
@sontopo  Or I can clean, if you don't want to install Dart SDK then let me know :)

**Comment by sontopo** [comment]
If you can do it, then sure, if not, when I get home I can try with the SDK
Enviado desde mi iPhone

El 25 oct 2023, a las 8:15, Shinya Kato ***@***.***> escribió:

﻿

@sontopo<https://github.com/sontopo> Or I can clean, if you don't want to install Dart SDK then let me know :)

**Comment by sontopo** [comment]
Could you please change the language name to it's original name? "Valencià" instead of Valencian, just like Spanish is called "Español".

**Comment by gildaswise** [comment]
@sontopo Done, I wasn't sure which name to use because I found conflicting results

**Pull request merged**
