### PR TITLE
Update strings_id.arb

### PR DESCRIPTION
**Pull request by moehammadiqbal1996**
I added id translation
 -'settingsAutoplayGIFs',
 -'searchTenor',
 -'settingsDisableGIFs'

Improvements, Fixes in Indonesian Translation

### CODE REVIEW

**Review by myConsciousness — APPROVED** [review]
@moehammadiqbal1996 Thank you!

**Comment by moehammadiqbal1996** [comment]
> @moehammadiqbal1996 Thank you!

> @myConsciousness For some reason I always make a mistake at the last 275 characters of line 3, is this sign } deleted first

**Comment by myConsciousness** [comment]
> > @moehammadiqbal1996 Thank you!
> 
> > @myConsciousness For some reason I always make a mistake at the last 275 characters of line 3, is this sign } deleted first

@moehammadiqbal1996 

Data in JSON format must not have a comma appended to the last row. So...

**This is correct:**

```json
{
  "key1": "value1",
  "key2": "value2"
}
```

**But this is not, because there is a comma in the last row:**

```json
{
  "key1": "value1",
  "key2": "value2",
}
```

**Comment by moehammadiqbal1996** [comment]
> > > @moehammadiqbal1996 Thank you!
> > 
> > 
> > > @myConsciousness For some reason I always make a mistake at the last 275 characters of line 3, is this sign } deleted first
> 
> @moehammadiqbal1996
> 
> Data in JSON format must not have a comma appended to the last row. So...
> 
> **This is correct:**
> 
> ```json
> {
>   "key1": "value1",
>   "key2": "value2"
> }
> ```
> 
> **But this is not, because there is a comma in the last row:**
> 
> ```json
> {
>   "key1": "value1",
>   "key2": "value2",
> }
> ```

@myConsciousness Thank you for the feedback and improvements. Hopefully in the next update I won't make any more mistakes, sorry for disturbing your time

**Pull request merged**
