### PR TITLE
Update strings_uk.arb

### PR DESCRIPTION
**Pull request by Andygol**
Updated Ukrainian translation.

PS 
Is there an option to add more than one translation for one language? In case, there is need to provide “pirate translation”.

### CODE REVIEW

**Comment by Andygol** [comment]
Since there is no "Issues" section, I've left it here.

Can you deploy translation support using dedicated translation services such as Transifex, Weblate, Crowdin, etc. to work on translations and keep them up-to-date?

**Comment by myConsciousness** [comment]
> Can you deploy translation support using dedicated translation services such as Transifex, Weblate, Crowdin, etc. to work on translations and keep them up-to-date?

I think such a management software is very useful, but the cost seems a bit high given our current monetization. But, once the number of users increases further and monetization stabilizes, of course these tools may be used in the future!

**Comment by myConsciousness** [comment]
> Updated Ukrainian translation.
> 
> PS Is there an option to add more than one translation for one language? In case, there is need to provide “pirate translation”.

Basically, I think we can only do one translation per language code. 

By the way, what is `Pirate Translation`? Does this translate like a PC game mod (fork)?

**Review by myConsciousness — APPROVED** [review]
I think this translation is very good, thank you!

**Comment by Andygol** [comment]
> By the way, what is `Pirate Translation`? Does this translate like a PC game mod (fork)?

In this context I mean that like on Wikipedia we have English and Simple English options, why not to allow having several variants of translation into one language.

While working on the translation, I had the idea to create a "Pirate Translation", a kind of humorous version of the interface elements. For example:

- Follow - bewitch (приворожити)
- Unfollow - let go (відпустити)
- Mute - to new brooms (до нових віників)
- Unmute - all over the throat (на все горло)
- Block - to curse (проклясти)
…
☝️ 
here I translated some idioms from Ukrainian to English

**Pull request merged**
